services:
  - name: docker:20.10.17-dind

variables:
  STACK_NAME: infra_canary

stages:
  - check_terraform

check_terraform:
  stage: check_terraform
  image: docker:20.10.17
  script:
    - apk add make
    - make stackrunner-build ST_RUNNER_VERSION=ci ST_RUNNER_TARGET_CPU_ARCH=amd64
    - make stack-check-fmt ST_RUNNER_VERSION=ci STACK_NAME=$(STACK_NAME)
