services:
  - name: docker:20.10.20-dind

variables:
  STACK_NAME: infra_canary

stages:
  - check_terraform

check_terraform:
  stage: check_terraform
  image: docker:20.10.20
  script:
    - apk add make
    - make stackrunner-info
    - make stackrunner-build ST_RUNNER_VERSION=ci
    # - make stack-check-fmt ST_RUNNER_VERSION=ci STACK_NAME=$(STACK_NAME)
