image: docker:20.10.20

services:
  - name: docker:20.10.20-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  ST_ENABLE_BACKEND: "false"
  ST_RUNNER_VERSION: ci
  STACK_NAME: infra_canary
  STACK_TOOLS_RUNNER_IMAGE: stacktools-runner:ci

stages:
  - check_terraform

check_terraform:
  stage: check_terraform
  script:
    - apk add make
    - make stackrunner-build
    - make stack-check-fmt
    - make stack-init
    - make stack-validate
