image: docker:20.10.20

services:
  - name: docker:20.10.20-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  STACK_NAME: infra_canary

stages:
  - check_terraform

check_terraform:
  stage: check_terraform
  script:
    - apk add make
    - make stackrunner-build ST_RUNNER_VERSION=ci
    - make stack-check-fmt STACK_TOOLS_RUNNER_IMAGE=stacktools-runner:ci STACK_NAME=$STACK_NAME
