stages:
  - check_terraform
  - validate_terraform

image: alpine:3.17.0

check_a:
  stage: check_terraform
  script:
    - apk add jq make
    - make stack-info STACK_NAME=app_ecr

validate_a:
  stage: validate_terraform
  script:
    - echo "This job validates ECR."
