image: docker:20.10.20

services:
  - name: docker:20.10.20-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  STACK_NAME: infra_canary
  STACK_TOOLS_RUNNER_IMAGE: stacktools-runner:ci

stages:
  - plan_terraform
  - apply_terraform

.prepare_tools_host:
  variables:
    ST_RUNNER_VERSION: ci
  before_script:
    - apk add jq make
    - make stackrunner-build

.plan_terraform:
  extends: .prepare_tools_host
  artifacts:
    when: on_success
    name: $STACK_NAME-tf-plan
    expire_in: 1 week
    paths:
      - terraform1/stacks/tmp/
  script:
    - make stack-init
    - make stack-plan

.apply_terraform:
  extends: .prepare_tools_host
  script:
    - make stack-init
    - make stack-apply

plan_terraform_dev:
  stage: plan_terraform
  extends:
    - .prepare_tools_host
    - .plan_terraform
  variables:
    ENVIRONMENT: dev

apply_terraform_dev:
  stage: apply_terraform
  dependencies:
    - plan_terraform_dev
  extends:
    - .prepare_tools_host
    - .apply_terraform
  variables:
    ENVIRONMENT: dev
