image: docker:20.10.20

services:
  - name: docker:20.10.20-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  STACK_NAME: infra_canary
  STACK_TOOLS_RUNNER_IMAGE: stacktools-runner:ci

stages:
  - plan_terraform
  - apply_terraform

.prepare_st_host:
  variables:
    ST_RUNNER_VERSION: ci
  before_script:
    - apk add jq make
    - make stackrunner-build

plan_terraform:
  stage: plan_terraform
  extends: .prepare_st_host
  variables:
    ENVIRONMENT: dev
  artifacts:
    name: $STACK_NAME-tf-plan
    expire_in: 1 week
    paths:
      - terraform1/stacks/tmp/
  script:
    - make stack-init
    - make stack-plan
    - make stack-plan-json

# apply_terraform:
#   stage: apply_terraform
#   extends: .prepare_st_host
#   variables:
#     ENVIRONMENT: dev
#   script:
#     - make stack-init
#     - make stack-apply
